aic_coco = [
    (
        0,
        6,
    ),
    (
        1,
        8,
    ),
    (
        2,
        10,
    ),
    (
        3,
        5,
    ),
    (
        4,
        7,
    ),
    (
        5,
        9,
    ),
    (
        6,
        12,
    ),
    (
        7,
        14,
    ),
    (
        8,
        16,
    ),
    (
        9,
        11,
    ),
    (
        10,
        13,
    ),
    (
        11,
        15,
    ),
]
auto_scale_lr = dict(base_batch_size=1024)
backend_args = dict(backend='local')
base_lr = 0.004
codec = dict(
    input_size=(
        192,
        256,
    ),
    normalize=False,
    sigma=(
        4.9,
        5.66,
    ),
    simcc_split_ratio=2.0,
    type='SimCCLabel',
    use_dark=False)
crowdpose_coco = [
    (
        0,
        5,
    ),
    (
        1,
        6,
    ),
    (
        2,
        7,
    ),
    (
        3,
        8,
    ),
    (
        4,
        9,
    ),
    (
        5,
        10,
    ),
    (
        6,
        11,
    ),
    (
        7,
        12,
    ),
    (
        8,
        13,
    ),
    (
        9,
        14,
    ),
    (
        10,
        15,
    ),
    (
        11,
        16,
    ),
]
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
    dict(
        switch_epoch=400,
        switch_pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(type='RandomHalfBody'),
            dict(
                rotate_factor=60,
                scale_factor=[
                    0.75,
                    1.25,
                ],
                shift_factor=0.0,
                type='RandomBBoxTransform'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=0.5,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        192,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        4.9,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='mmdet.PipelineSwitchHook'),
]
data_mode = 'topdown'
data_root = 'data/'
dataset_aic = dict(
    ann_file='aic/annotations/aic_train.json',
    data_mode='topdown',
    data_prefix=dict(
        img=
        'pose/ai_challenge/ai_challenger_keypoint_train_20170902/keypoint_train_images_20170902/'
    ),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    6,
                ),
                (
                    1,
                    8,
                ),
                (
                    2,
                    10,
                ),
                (
                    3,
                    5,
                ),
                (
                    4,
                    7,
                ),
                (
                    5,
                    9,
                ),
                (
                    6,
                    12,
                ),
                (
                    7,
                    14,
                ),
                (
                    8,
                    16,
                ),
                (
                    9,
                    11,
                ),
                (
                    10,
                    13,
                ),
                (
                    11,
                    15,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='AicDataset')
dataset_coco = dict(
    ann_file='coco/annotations/person_keypoints_train2017.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/train2017/'),
    data_root='data/',
    pipeline=[],
    type='CocoDataset')
dataset_crowdpose = dict(
    ann_file='crowdpose/annotations/mmpose_crowdpose_trainval.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/CrowdPose/images/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    5,
                ),
                (
                    1,
                    6,
                ),
                (
                    2,
                    7,
                ),
                (
                    3,
                    8,
                ),
                (
                    4,
                    9,
                ),
                (
                    5,
                    10,
                ),
                (
                    6,
                    11,
                ),
                (
                    7,
                    12,
                ),
                (
                    8,
                    13,
                ),
                (
                    9,
                    14,
                ),
                (
                    10,
                    15,
                ),
                (
                    11,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='CrowdPoseDataset')
dataset_halpe = dict(
    ann_file='halpe/annotations/halpe_train_v1.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/Halpe/hico_20160224_det/images/train2015'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    1,
                    1,
                ),
                (
                    2,
                    2,
                ),
                (
                    3,
                    3,
                ),
                (
                    4,
                    4,
                ),
                (
                    5,
                    5,
                ),
                (
                    6,
                    6,
                ),
                (
                    7,
                    7,
                ),
                (
                    8,
                    8,
                ),
                (
                    9,
                    9,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    11,
                ),
                (
                    12,
                    12,
                ),
                (
                    13,
                    13,
                ),
                (
                    14,
                    14,
                ),
                (
                    15,
                    15,
                ),
                (
                    16,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='HalpeDataset')
dataset_jhmdb = dict(
    ann_file='jhmdb/annotations/Sub1_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/JHMDB/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    3,
                    6,
                ),
                (
                    4,
                    5,
                ),
                (
                    5,
                    12,
                ),
                (
                    6,
                    11,
                ),
                (
                    7,
                    8,
                ),
                (
                    8,
                    7,
                ),
                (
                    9,
                    14,
                ),
                (
                    10,
                    13,
                ),
                (
                    11,
                    10,
                ),
                (
                    12,
                    9,
                ),
                (
                    13,
                    16,
                ),
                (
                    14,
                    15,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='JhmdbDataset')
dataset_mpii = dict(
    ann_file='mpii/annotations/mpii_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/MPI/images/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    16,
                ),
                (
                    1,
                    14,
                ),
                (
                    2,
                    12,
                ),
                (
                    3,
                    11,
                ),
                (
                    4,
                    13,
                ),
                (
                    5,
                    15,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    8,
                ),
                (
                    12,
                    6,
                ),
                (
                    13,
                    5,
                ),
                (
                    14,
                    7,
                ),
                (
                    15,
                    9,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='MpiiDataset')
dataset_posetrack = dict(
    ann_file='posetrack18/annotations/posetrack18_train.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/PoseChallenge2018/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    3,
                    3,
                ),
                (
                    4,
                    4,
                ),
                (
                    5,
                    5,
                ),
                (
                    6,
                    6,
                ),
                (
                    7,
                    7,
                ),
                (
                    8,
                    8,
                ),
                (
                    9,
                    9,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    11,
                ),
                (
                    12,
                    12,
                ),
                (
                    13,
                    13,
                ),
                (
                    14,
                    14,
                ),
                (
                    15,
                    15,
                ),
                (
                    16,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='PoseTrack18Dataset')
dataset_type = 'CocoDataset'
default_hooks = dict(
    badcase=dict(
        badcase_thr=5,
        enable=False,
        metric_type='loss',
        out_dir='badcase',
        type='BadCaseAnalysisHook'),
    checkpoint=dict(
        interval=10,
        max_keep_ckpts=1,
        rule='greater',
        save_best='coco/AP',
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(enable=False, type='PoseVisualizationHook'))
default_scope = 'mmpose'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
halpe_coco = [
    (
        0,
        0,
    ),
    (
        1,
        1,
    ),
    (
        2,
        2,
    ),
    (
        3,
        3,
    ),
    (
        4,
        4,
    ),
    (
        5,
        5,
    ),
    (
        6,
        6,
    ),
    (
        7,
        7,
    ),
    (
        8,
        8,
    ),
    (
        9,
        9,
    ),
    (
        10,
        10,
    ),
    (
        11,
        11,
    ),
    (
        12,
        12,
    ),
    (
        13,
        13,
    ),
    (
        14,
        14,
    ),
    (
        15,
        15,
    ),
    (
        16,
        16,
    ),
]
jhmdb_coco = [
    (
        3,
        6,
    ),
    (
        4,
        5,
    ),
    (
        5,
        12,
    ),
    (
        6,
        11,
    ),
    (
        7,
        8,
    ),
    (
        8,
        7,
    ),
    (
        9,
        14,
    ),
    (
        10,
        13,
    ),
    (
        11,
        10,
    ),
    (
        12,
        9,
    ),
    (
        13,
        16,
    ),
    (
        14,
        15,
    ),
]
load_from = None
log_level = 'INFO'
log_processor = dict(
    by_epoch=True, num_digits=6, type='LogProcessor', window_size=50)
max_epochs = 420
model = dict(
    backbone=dict(
        _scope_='mmdet',
        act_cfg=dict(type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=0.33,
        expand_ratio=0.5,
        init_cfg=dict(
            checkpoint=
            'https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/cspnext-s_udp-body7_210e-256x192-8c9ccbdb_20230504.pth',
            prefix='backbone.',
            type='Pretrained'),
        norm_cfg=dict(type='SyncBN'),
        out_indices=(4, ),
        type='CSPNeXt',
        widen_factor=0.5),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='PoseDataPreprocessor'),
    head=dict(
        decoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        final_layer_kernel_size=7,
        gau_cfg=dict(
            act_fn='SiLU',
            drop_path=0.0,
            dropout_rate=0.0,
            expansion_factor=2,
            hidden_dims=256,
            pos_enc=False,
            s=128,
            use_rel_bias=False),
        in_channels=512,
        in_featuremap_size=(
            6,
            8,
        ),
        input_size=(
            192,
            256,
        ),
        loss=dict(
            beta=10.0,
            label_softmax=True,
            type='KLDiscretLoss',
            use_target_weight=True),
        out_channels=17,
        simcc_split_ratio=2.0,
        type='RTMCCHead'),
    test_cfg=dict(flip_test=True),
    type='TopdownPoseEstimator')
mpii_coco = [
    (
        0,
        16,
    ),
    (
        1,
        14,
    ),
    (
        2,
        12,
    ),
    (
        3,
        11,
    ),
    (
        4,
        13,
    ),
    (
        5,
        15,
    ),
    (
        10,
        10,
    ),
    (
        11,
        8,
    ),
    (
        12,
        6,
    ),
    (
        13,
        5,
    ),
    (
        14,
        7,
    ),
    (
        15,
        9,
    ),
]
ochuman_coco = [
    (
        0,
        0,
    ),
    (
        1,
        1,
    ),
    (
        2,
        2,
    ),
    (
        3,
        3,
    ),
    (
        4,
        4,
    ),
    (
        5,
        5,
    ),
    (
        6,
        6,
    ),
    (
        7,
        7,
    ),
    (
        8,
        8,
    ),
    (
        9,
        9,
    ),
    (
        10,
        10,
    ),
    (
        11,
        11,
    ),
    (
        12,
        12,
    ),
    (
        13,
        13,
    ),
    (
        14,
        14,
    ),
    (
        15,
        15,
    ),
    (
        16,
        16,
    ),
]
optim_wrapper = dict(
    optimizer=dict(lr=0.004, type='AdamW', weight_decay=0.0),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1000, start_factor=1e-05,
        type='LinearLR'),
    dict(
        T_max=210,
        begin=210,
        by_epoch=True,
        convert_to_iter_based=True,
        end=420,
        eta_min=0.0002,
        type='CosineAnnealingLR'),
]
posetrack_coco = [
    (
        0,
        0,
    ),
    (
        3,
        3,
    ),
    (
        4,
        4,
    ),
    (
        5,
        5,
    ),
    (
        6,
        6,
    ),
    (
        7,
        7,
    ),
    (
        8,
        8,
    ),
    (
        9,
        9,
    ),
    (
        10,
        10,
    ),
    (
        11,
        11,
    ),
    (
        12,
        12,
    ),
    (
        13,
        13,
    ),
    (
        14,
        14,
    ),
    (
        15,
        15,
    ),
    (
        16,
        16,
    ),
]
randomness = dict(seed=21)
resume = False
stage2_num_epochs = 20
test_cfg = dict()
test_dataloader = dict(
    batch_size=64,
    dataset=dict(
        datasets=[
            dict(
                ann_file='coco/annotations/person_keypoints_val2017.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[],
                type='CocoDataset'),
            dict(
                ann_file='aic/annotations/aic_val.json',
                data_mode='topdown',
                data_prefix=dict(
                    img=
                    'pose/ai_challenge/ai_challenger_keypoint_validation_20170911/keypoint_validation_images_20170911/'
                ),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                6,
                            ),
                            (
                                1,
                                8,
                            ),
                            (
                                2,
                                10,
                            ),
                            (
                                3,
                                5,
                            ),
                            (
                                4,
                                7,
                            ),
                            (
                                5,
                                9,
                            ),
                            (
                                6,
                                12,
                            ),
                            (
                                7,
                                14,
                            ),
                            (
                                8,
                                16,
                            ),
                            (
                                9,
                                11,
                            ),
                            (
                                10,
                                13,
                            ),
                            (
                                11,
                                15,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='AicDataset'),
            dict(
                ann_file='crowdpose/annotations/mmpose_crowdpose_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/CrowdPose/images/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                5,
                            ),
                            (
                                1,
                                6,
                            ),
                            (
                                2,
                                7,
                            ),
                            (
                                3,
                                8,
                            ),
                            (
                                4,
                                9,
                            ),
                            (
                                5,
                                10,
                            ),
                            (
                                6,
                                11,
                            ),
                            (
                                7,
                                12,
                            ),
                            (
                                8,
                                13,
                            ),
                            (
                                9,
                                14,
                            ),
                            (
                                10,
                                15,
                            ),
                            (
                                11,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='CrowdPoseDataset'),
            dict(
                ann_file='mpii/annotations/mpii_val.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/MPI/images/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                16,
                            ),
                            (
                                1,
                                14,
                            ),
                            (
                                2,
                                12,
                            ),
                            (
                                3,
                                11,
                            ),
                            (
                                4,
                                13,
                            ),
                            (
                                5,
                                15,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                8,
                            ),
                            (
                                12,
                                6,
                            ),
                            (
                                13,
                                5,
                            ),
                            (
                                14,
                                7,
                            ),
                            (
                                15,
                                9,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='MpiiDataset'),
            dict(
                ann_file='jhmdb/annotations/Sub1_test.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/JHMDB/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                3,
                                6,
                            ),
                            (
                                4,
                                5,
                            ),
                            (
                                5,
                                12,
                            ),
                            (
                                6,
                                11,
                            ),
                            (
                                7,
                                8,
                            ),
                            (
                                8,
                                7,
                            ),
                            (
                                9,
                                14,
                            ),
                            (
                                10,
                                13,
                            ),
                            (
                                11,
                                10,
                            ),
                            (
                                12,
                                9,
                            ),
                            (
                                13,
                                16,
                            ),
                            (
                                14,
                                15,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='JhmdbDataset'),
            dict(
                ann_file='halpe/annotations/halpe_val_v1.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/val2017/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                1,
                            ),
                            (
                                2,
                                2,
                            ),
                            (
                                3,
                                3,
                            ),
                            (
                                4,
                                4,
                            ),
                            (
                                5,
                                5,
                            ),
                            (
                                6,
                                6,
                            ),
                            (
                                7,
                                7,
                            ),
                            (
                                8,
                                8,
                            ),
                            (
                                9,
                                9,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                11,
                            ),
                            (
                                12,
                                12,
                            ),
                            (
                                13,
                                13,
                            ),
                            (
                                14,
                                14,
                            ),
                            (
                                15,
                                15,
                            ),
                            (
                                16,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='HalpeDataset'),
            dict(
                ann_file=
                'ochuman/annotations/ochuman_coco_format_val_range_0.00_1.00.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/OCHuman/images/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                1,
                            ),
                            (
                                2,
                                2,
                            ),
                            (
                                3,
                                3,
                            ),
                            (
                                4,
                                4,
                            ),
                            (
                                5,
                                5,
                            ),
                            (
                                6,
                                6,
                            ),
                            (
                                7,
                                7,
                            ),
                            (
                                8,
                                8,
                            ),
                            (
                                9,
                                9,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                11,
                            ),
                            (
                                12,
                                12,
                            ),
                            (
                                13,
                                13,
                            ),
                            (
                                14,
                                14,
                            ),
                            (
                                15,
                                15,
                            ),
                            (
                                16,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='OCHumanDataset'),
            dict(
                ann_file='posetrack18/annotations/posetrack18_val.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/PoseChallenge2018/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                3,
                                3,
                            ),
                            (
                                4,
                                4,
                            ),
                            (
                                5,
                                5,
                            ),
                            (
                                6,
                                6,
                            ),
                            (
                                7,
                                7,
                            ),
                            (
                                8,
                                8,
                            ),
                            (
                                9,
                                9,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                11,
                            ),
                            (
                                12,
                                12,
                            ),
                            (
                                13,
                                13,
                            ),
                            (
                                14,
                                14,
                            ),
                            (
                                15,
                                15,
                            ),
                            (
                                16,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='PoseTrack18Dataset'),
        ],
        metainfo=dict(from_file='configs/_base_/datasets/coco.py'),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CombinedDataset'),
    drop_last=False,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = [
    dict(thr=0.1, type='PCKAccuracy'),
    dict(type='AUC'),
    dict(type='EPE'),
]
train_cfg = dict(by_epoch=True, max_epochs=420, val_interval=10)
train_dataloader = dict(
    batch_size=256,
    dataset=dict(
        datasets=[
            dict(
                ann_file='coco/annotations/person_keypoints_train2017.json',
                data_mode='topdown',
                data_prefix=dict(img='detection/coco/train2017/'),
                data_root='data/',
                pipeline=[],
                type='CocoDataset'),
            dict(
                ann_file='aic/annotations/aic_train.json',
                data_mode='topdown',
                data_prefix=dict(
                    img=
                    'pose/ai_challenge/ai_challenger_keypoint_train_20170902/keypoint_train_images_20170902/'
                ),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                6,
                            ),
                            (
                                1,
                                8,
                            ),
                            (
                                2,
                                10,
                            ),
                            (
                                3,
                                5,
                            ),
                            (
                                4,
                                7,
                            ),
                            (
                                5,
                                9,
                            ),
                            (
                                6,
                                12,
                            ),
                            (
                                7,
                                14,
                            ),
                            (
                                8,
                                16,
                            ),
                            (
                                9,
                                11,
                            ),
                            (
                                10,
                                13,
                            ),
                            (
                                11,
                                15,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='AicDataset'),
            dict(
                ann_file='crowdpose/annotations/mmpose_crowdpose_trainval.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/CrowdPose/images/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                5,
                            ),
                            (
                                1,
                                6,
                            ),
                            (
                                2,
                                7,
                            ),
                            (
                                3,
                                8,
                            ),
                            (
                                4,
                                9,
                            ),
                            (
                                5,
                                10,
                            ),
                            (
                                6,
                                11,
                            ),
                            (
                                7,
                                12,
                            ),
                            (
                                8,
                                13,
                            ),
                            (
                                9,
                                14,
                            ),
                            (
                                10,
                                15,
                            ),
                            (
                                11,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='CrowdPoseDataset'),
            dict(
                ann_file='mpii/annotations/mpii_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/MPI/images/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                16,
                            ),
                            (
                                1,
                                14,
                            ),
                            (
                                2,
                                12,
                            ),
                            (
                                3,
                                11,
                            ),
                            (
                                4,
                                13,
                            ),
                            (
                                5,
                                15,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                8,
                            ),
                            (
                                12,
                                6,
                            ),
                            (
                                13,
                                5,
                            ),
                            (
                                14,
                                7,
                            ),
                            (
                                15,
                                9,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='MpiiDataset'),
            dict(
                ann_file='jhmdb/annotations/Sub1_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/JHMDB/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                3,
                                6,
                            ),
                            (
                                4,
                                5,
                            ),
                            (
                                5,
                                12,
                            ),
                            (
                                6,
                                11,
                            ),
                            (
                                7,
                                8,
                            ),
                            (
                                8,
                                7,
                            ),
                            (
                                9,
                                14,
                            ),
                            (
                                10,
                                13,
                            ),
                            (
                                11,
                                10,
                            ),
                            (
                                12,
                                9,
                            ),
                            (
                                13,
                                16,
                            ),
                            (
                                14,
                                15,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='JhmdbDataset'),
            dict(
                ann_file='halpe/annotations/halpe_train_v1.json',
                data_mode='topdown',
                data_prefix=dict(
                    img='pose/Halpe/hico_20160224_det/images/train2015'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                1,
                                1,
                            ),
                            (
                                2,
                                2,
                            ),
                            (
                                3,
                                3,
                            ),
                            (
                                4,
                                4,
                            ),
                            (
                                5,
                                5,
                            ),
                            (
                                6,
                                6,
                            ),
                            (
                                7,
                                7,
                            ),
                            (
                                8,
                                8,
                            ),
                            (
                                9,
                                9,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                11,
                            ),
                            (
                                12,
                                12,
                            ),
                            (
                                13,
                                13,
                            ),
                            (
                                14,
                                14,
                            ),
                            (
                                15,
                                15,
                            ),
                            (
                                16,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='HalpeDataset'),
            dict(
                ann_file='posetrack18/annotations/posetrack18_train.json',
                data_mode='topdown',
                data_prefix=dict(img='pose/PoseChallenge2018/'),
                data_root='data/',
                pipeline=[
                    dict(
                        mapping=[
                            (
                                0,
                                0,
                            ),
                            (
                                3,
                                3,
                            ),
                            (
                                4,
                                4,
                            ),
                            (
                                5,
                                5,
                            ),
                            (
                                6,
                                6,
                            ),
                            (
                                7,
                                7,
                            ),
                            (
                                8,
                                8,
                            ),
                            (
                                9,
                                9,
                            ),
                            (
                                10,
                                10,
                            ),
                            (
                                11,
                                11,
                            ),
                            (
                                12,
                                12,
                            ),
                            (
                                13,
                                13,
                            ),
                            (
                                14,
                                14,
                            ),
                            (
                                15,
                                15,
                            ),
                            (
                                16,
                                16,
                            ),
                        ],
                        num_keypoints=17,
                        type='KeypointConverter'),
                ],
                type='PoseTrack18Dataset'),
        ],
        metainfo=dict(from_file='configs/_base_/datasets/coco.py'),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(type='RandomHalfBody'),
            dict(
                rotate_factor=80,
                scale_factor=[
                    0.6,
                    1.4,
                ],
                type='RandomBBoxTransform'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(type='PhotometricDistortion'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=1.0,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        192,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        4.9,
                        5.66,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=False,
        type='CombinedDataset'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(type='RandomHalfBody'),
    dict(
        rotate_factor=80,
        scale_factor=[
            0.6,
            1.4,
        ],
        type='RandomBBoxTransform'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(type='PhotometricDistortion'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=1.0,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
train_pipeline_stage2 = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(type='RandomHalfBody'),
    dict(
        rotate_factor=60,
        scale_factor=[
            0.75,
            1.25,
        ],
        shift_factor=0.0,
        type='RandomBBoxTransform'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=0.5,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                192,
                256,
            ),
            normalize=False,
            sigma=(
                4.9,
                5.66,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
val_aic = dict(
    ann_file='aic/annotations/aic_val.json',
    data_mode='topdown',
    data_prefix=dict(
        img=
        'pose/ai_challenge/ai_challenger_keypoint_validation_20170911/keypoint_validation_images_20170911/'
    ),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    6,
                ),
                (
                    1,
                    8,
                ),
                (
                    2,
                    10,
                ),
                (
                    3,
                    5,
                ),
                (
                    4,
                    7,
                ),
                (
                    5,
                    9,
                ),
                (
                    6,
                    12,
                ),
                (
                    7,
                    14,
                ),
                (
                    8,
                    16,
                ),
                (
                    9,
                    11,
                ),
                (
                    10,
                    13,
                ),
                (
                    11,
                    15,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='AicDataset')
val_cfg = dict()
val_coco = dict(
    ann_file='coco/annotations/person_keypoints_val2017.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/val2017/'),
    data_root='data/',
    pipeline=[],
    type='CocoDataset')
val_crowdpose = dict(
    ann_file='crowdpose/annotations/mmpose_crowdpose_test.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/CrowdPose/images/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    5,
                ),
                (
                    1,
                    6,
                ),
                (
                    2,
                    7,
                ),
                (
                    3,
                    8,
                ),
                (
                    4,
                    9,
                ),
                (
                    5,
                    10,
                ),
                (
                    6,
                    11,
                ),
                (
                    7,
                    12,
                ),
                (
                    8,
                    13,
                ),
                (
                    9,
                    14,
                ),
                (
                    10,
                    15,
                ),
                (
                    11,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='CrowdPoseDataset')
val_dataloader = dict(
    batch_size=64,
    dataset=dict(
        ann_file='coco/annotations/person_keypoints_val2017.json',
        bbox_file=
        'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json',
        data_mode='topdown',
        data_prefix=dict(img='detection/coco/val2017/'),
        data_root='data/',
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                192,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=10,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='data/coco/annotations/person_keypoints_val2017.json',
    type='CocoMetric')
val_halpe = dict(
    ann_file='halpe/annotations/halpe_val_v1.json',
    data_mode='topdown',
    data_prefix=dict(img='detection/coco/val2017/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    1,
                    1,
                ),
                (
                    2,
                    2,
                ),
                (
                    3,
                    3,
                ),
                (
                    4,
                    4,
                ),
                (
                    5,
                    5,
                ),
                (
                    6,
                    6,
                ),
                (
                    7,
                    7,
                ),
                (
                    8,
                    8,
                ),
                (
                    9,
                    9,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    11,
                ),
                (
                    12,
                    12,
                ),
                (
                    13,
                    13,
                ),
                (
                    14,
                    14,
                ),
                (
                    15,
                    15,
                ),
                (
                    16,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='HalpeDataset')
val_jhmdb = dict(
    ann_file='jhmdb/annotations/Sub1_test.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/JHMDB/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    3,
                    6,
                ),
                (
                    4,
                    5,
                ),
                (
                    5,
                    12,
                ),
                (
                    6,
                    11,
                ),
                (
                    7,
                    8,
                ),
                (
                    8,
                    7,
                ),
                (
                    9,
                    14,
                ),
                (
                    10,
                    13,
                ),
                (
                    11,
                    10,
                ),
                (
                    12,
                    9,
                ),
                (
                    13,
                    16,
                ),
                (
                    14,
                    15,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='JhmdbDataset')
val_mpii = dict(
    ann_file='mpii/annotations/mpii_val.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/MPI/images/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    16,
                ),
                (
                    1,
                    14,
                ),
                (
                    2,
                    12,
                ),
                (
                    3,
                    11,
                ),
                (
                    4,
                    13,
                ),
                (
                    5,
                    15,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    8,
                ),
                (
                    12,
                    6,
                ),
                (
                    13,
                    5,
                ),
                (
                    14,
                    7,
                ),
                (
                    15,
                    9,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='MpiiDataset')
val_ochuman = dict(
    ann_file='ochuman/annotations/ochuman_coco_format_val_range_0.00_1.00.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/OCHuman/images/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    1,
                    1,
                ),
                (
                    2,
                    2,
                ),
                (
                    3,
                    3,
                ),
                (
                    4,
                    4,
                ),
                (
                    5,
                    5,
                ),
                (
                    6,
                    6,
                ),
                (
                    7,
                    7,
                ),
                (
                    8,
                    8,
                ),
                (
                    9,
                    9,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    11,
                ),
                (
                    12,
                    12,
                ),
                (
                    13,
                    13,
                ),
                (
                    14,
                    14,
                ),
                (
                    15,
                    15,
                ),
                (
                    16,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='OCHumanDataset')
val_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(input_size=(
        192,
        256,
    ), type='TopdownAffine'),
    dict(type='PackPoseInputs'),
]
val_posetrack = dict(
    ann_file='posetrack18/annotations/posetrack18_val.json',
    data_mode='topdown',
    data_prefix=dict(img='pose/PoseChallenge2018/'),
    data_root='data/',
    pipeline=[
        dict(
            mapping=[
                (
                    0,
                    0,
                ),
                (
                    3,
                    3,
                ),
                (
                    4,
                    4,
                ),
                (
                    5,
                    5,
                ),
                (
                    6,
                    6,
                ),
                (
                    7,
                    7,
                ),
                (
                    8,
                    8,
                ),
                (
                    9,
                    9,
                ),
                (
                    10,
                    10,
                ),
                (
                    11,
                    11,
                ),
                (
                    12,
                    12,
                ),
                (
                    13,
                    13,
                ),
                (
                    14,
                    14,
                ),
                (
                    15,
                    15,
                ),
                (
                    16,
                    16,
                ),
            ],
            num_keypoints=17,
            type='KeypointConverter'),
    ],
    type='PoseTrack18Dataset')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
